-- MySQL Script generated by MySQL Workbench
-- Tue Oct 24 11:39:56 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tradeDb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tradeDb` DEFAULT CHARACTER SET latin1;
USE `tradeDb`;

CREATE TABLE `tradeDb`.`bot`
(
   `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name`   VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `name`)
) ENGINE =InnoDB DEFAULT CHARSET = latin1;
